### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Sajito** [Ploppy3/translation-manager#1]
Hi,

I've found this project mentioned in the ngx-translate/core README.
I wonder if I am allowed to host it on my own or modify it.

Unfortunately there is no license in the package.json.

I'm specifically interested in knowing if I am allowed to modify and use the project commercially.

Thank you!

**Comment by Ploppy3** [comment]
Hello, I added the licence to the `package.json`.

If you are interested in my work check my [curriculum vitae](https://cv.engin9tools.com/) !
I am currently looking for a job !

Thanks !
